# Sử dụng image .NET SDK để build ứng dụng
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Sao chép tất cả các project và restore dependencies
COPY *.sln .
COPY EventFlowerExchange.API/EventFlowerExchange.API.csproj EventFlowerExchange.API/
COPY EventFlowerExchange.Application/EventFlowerExchange.Application.csproj EventFlowerExchange.Application/
COPY EventFlowerExchange.Infrastructure/EventFlowerExchange.Infrastructure.csproj EventFlowerExchange.Infrastructure/
COPY EventFlowerExchange.Domain/EventFlowerExchange.Domain.csproj EventFlowerExchange.Domain/

RUN dotnet restore

# Sao chép mã nguồn và build ứng dụng
COPY . .
RUN dotnet publish EventFlowerExchange.API/EventFlowerExchange.API.csproj -c Release -o out

# Tạo image runtime
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .

# Thiết lập lệnh chạy ứng dụng
ENTRYPOINT ["dotnet", "EventFlowerExchange.API.dll"]
